//@ui5-bundle com/mycompany/myapp/Component-preload.js
sap.ui.predefine("com/mycompany/myapp/Component", ["sap/ui/core/UIComponent"],function(n){"use strict";return n.extend("com.mycompany.myapp.Component",{metadata:{manifest:"json"},init:function(){n.prototype.init.apply(this,arguments)}})});
sap.ui.predefine("com/mycompany/myapp/controller/Main.controller", ["sap/ui/core/mvc/Controller","sap/ui/model/json/JSONModel"],function(e,t){"use strict";return e.extend("com.mycompany.myapp.controller.Main",{onInit:function(){this._adjustLayout();sap.ui.Device.resize.attachHandler(this._adjustLayout,this)},_adjustLayout:function(){var e=this.getView();var i=new t({isPhone:sap.ui.Device.system.phone,isTablet:sap.ui.Device.system.tablet,isDesktop:sap.ui.Device.system.desktop});e.setModel(i,"device")},onExit:function(){sap.ui.Device.resize.detachHandler(this._adjustLayout,this)}})});
sap.ui.require.preload({
	"com/mycompany/myapp/i18n/i18n.properties":'appTitle=Spenden-App\r\nappDescription=Eine Anwendung zum Spenden via PayPal\r\npageTitle=Spenden\r\ndonationTitle=Unterst\\u00fctzen Sie unser Projekt\r\ndonationDescription=Ihre Spende hilft uns\r\ndonationText=Ihre Spende hilft uns, unsere Arbeit fortzusetzen. Jeder Beitrag, egal wie gro\\u00df oder klein, macht einen Unterschied. Vielen Dank f\\u00fcr Ihre Unterst\\u00fctzung!',
	"com/mycompany/myapp/manifest.json":'{"_version":"1.12.0","sap.app":{"id":"com.mycompany.myapp","type":"application","i18n":"i18n/i18n.properties","title":"{{appTitle}}","description":"{{appDescription}}","applicationVersion":{"version":"1.0.0"}},"sap.ui":{"technology":"UI5","deviceTypes":{"desktop":true,"tablet":true,"phone":true}},"sap.ui5":{"rootView":{"viewName":"com.mycompany.myapp.view.Main","type":"XML","async":true,"id":"app"},"dependencies":{"minUI5Version":"1.60.0","libs":{"sap.m":{},"sap.ui.core":{}}},"models":{"i18n":{"type":"sap.ui.model.resource.ResourceModel","settings":{"bundleName":"com.mycompany.myapp.i18n.i18n"}}}}}',
	"com/mycompany/myapp/view/Main.view.xml":'<mvc:View\r\n   controllerName="com.mycompany.myapp.controller.Main"\r\n   xmlns:mvc="sap.ui.core.mvc"\r\n   xmlns="sap.m"\r\n   xmlns:l="sap.ui.layout"\r\n   xmlns:f="sap.ui.layout.form"\r\n   xmlns:core="sap.ui.core"><App><pages><Page title="{i18n>pageTitle}" class="sapUiResponsiveContentPadding"><content><l:VerticalLayout width="100%" class="sapUiContentPadding"><l:content><f:SimpleForm editable="false" layout="ResponsiveGridLayout" \r\n                        labelSpanXL="4" labelSpanL="4" labelSpanM="12" labelSpanS="12" \r\n                        adjustLabelSpan="false" emptySpanXL="0" emptySpanL="0" emptySpanM="0" emptySpanS="0" \r\n                        columnsXL="1" columnsL="1" columnsM="1" \r\n                        singleContainerFullSize="false"><f:content><core:Title text="{i18n>donationTitle}" /><Label text="{i18n>donationDescription}" /><Text text="{i18n>donationText}" /><core:HTML content=\'&lt;form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top"&gt;\r\n                              &lt;input type="hidden" name="cmd" value="_donations" /&gt;\r\n                              &lt;input type="hidden" name="business" value="alvar.aalto@web.de" /&gt;\r\n                              &lt;input type="hidden" name="currency_code" value="EUR" /&gt;\r\n                              &lt;input type="image" src="https://www.paypalobjects.com/de_DE/DE/i/btn/btn_donateCC_LG.gif" border="0" name="submit" title="PayPal - The safer, easier way to pay online!" alt="Spenden mit dem PayPal-Button" /&gt;\r\n                           &lt;/form&gt;\' /></f:content></f:SimpleForm></l:content></l:VerticalLayout></content></Page></pages></App></mvc:View>'
});
//# sourceMappingURL=Component-preload.js.map
